# Use the official Node.js 14 image as the base image
FROM node:17

# Set the working directory inside the container to /app
WORKDIR /app

# Copy package.json and package-lock.json (if present) to /app
# COPY package*.json ./

# Install dependencies
RUN npm install bcrypt cors dotenv ejs express express-winston ioredis jsonwebtoken moment mongoose multer node-emoji nodemailer nodemon perr socket.io uuid winston

# Copy all files from the current directory to /app in the container
COPY . /app

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run when the container starts
CMD ["node", "index.js"]